name: Custom Check
on:
  pull_request:
  workflow_dispatch: # This allows manual triggering of the workflow with specific inputs
    inputs:
      status: # Define the input parameter
        description: "Status from external service"
        required: true
        default: "pending"

jobs:
  custom_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Custom Check
        env:
          STATUS_FROM_EXTERNAL: ${{ github.event.inputs.status }} # Read the input value from the workflow dispatch
        run: |
          # ... Your logic to determine the status based on $STATUS_FROM_EXTERNAL ...
          # status="success" or status="failure" or status="pending"

          # Set the check status for the workflow itself based on the status value.
          if [ "$STATUS_FROM_EXTERNAL" = "success" ]; then
            echo "The custom check succeeded."
          elif [ "$STATUS_FROM_EXTERNAL" = "failure" ]; then
            echo "The custom check failed."
            exit 1 # Exit with a non-zero status to indicate a failure
          else
            echo "The custom check is pending."
          fi
